tasks:
  - name: update-user-email
    title: Update User's Email
    description: Update a user's email address.
    db:
      connection: users
      sql: update users set email = :email where id = :id
    schema:
      properties:
        id:
          type: integer
        email:
          pattern: '@'
          type: string
